# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#import PySide2.scripts.pyside_tool
#from PySide2 import QtCore, QtGui
#from PySide2.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from kark import Ui_MainWindow
#from desk import Ui_MainWindow1
#from main import MyWindow
class Ui_MainWindow2(object):
   def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStyleSheet("background-color:gainsboro;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 300, 201, 201))
        self.label_2.setStyleSheet("QPushButton{\n"
        "background-color:222e;\n"
        "border:30;\n"
        "}\n"
        "QPushButton::{\n"
        "background-color:black;\n"
        "}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("reg1.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 0, 201, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("reg2.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 2, 201, 201))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
        "background-color:222e;\n"
        "border:30;\n"
        "}\n"
        "QPushButton::pressed{\n"
        "background-color:black;\n"
        "}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 300, 201, 201))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
        "background-color:222e;\n"
        "border:30;\n"
        "}\n"
        "QPushButton::pressed{\n"
        "background-color:black;\n"
        "}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 200, 141, 20))
        font = QtGui.QFont()
        font.setFamily("OpenDyslexicAlta")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 270, 71, 17))
        font = QtGui.QFont()
        font.setFamily("OpenDyslexicAlta")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 381, 20))
        font = QtGui.QFont()
        font.setFamily("OpenDyslexicAlta")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        #self.pushButton.clicked.connect(MainWindow.)

        self.pushButton_2.clicked.connect(MainWindow.maps)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
   def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Администратор"))
        self.label_4.setText(_translate("MainWindow", "Клиент"))
        self.label_5.setText(_translate("MainWindow", "Авторизация                  пользователя"))

#def main():
 #   import sys
 #   app = QApplication(sys.argv)
 #   MainWindow = QMainWindow()
 #   ui = Ui_MainWindow2()
 #   ui.setupUi(MainWindow)
  #  MainWindow.show()
 #   sys.exit(app.exec_())
#if __name__ == "__main__":
  #  main()
